In [1]:
def load_file(file_path: str) -> dict:
    """
    從劉子揚生成的各種 instance 檔案中讀取資料 \\
    param: file_path: 檔案路徑，直接放例如 "Instances/Group1/Instance1_0.xlsx" 就可以了 \\
    return: 讀取的資料
    """

    import pandas as pd
    import numpy as np  

    ### 從 Excel檔案讀取資料存成 dataframe ###
    df_basic = pd.read_excel(file_path, sheet_name='Basic', index_col=0, header=0)

    df_hotel_time = pd.read_excel(file_path, sheet_name='Hotel_Time', index_col=0, header=0)
    df_hotel_cost = pd.read_excel(file_path, sheet_name='Hotel_Cost', index_col=0, header=0)

    df_attraction_cost = pd.read_excel(file_path, sheet_name='Attraction_Cost', index_col=0, header=0)
    df_attrcation_open = pd.read_excel(file_path, sheet_name='Attraction_Open', index_col=0, header=0)
    df_attrcation_close = pd.read_excel(file_path, sheet_name='Attraction_Close', index_col=0, header=0)

    df_walk_time = pd.read_excel(file_path, sheet_name='Walk_Time', index_col=0, header=0)
    df_train_time = pd.read_excel(file_path, sheet_name='Train_Time', index_col=0, header=0)
    df_car_time = pd.read_excel(file_path, sheet_name='Car_Time', index_col=0, header=0)

    df_train_cost = pd.read_excel(file_path, sheet_name='Train_Cost', index_col=0, header=0)
    df_car_cost = pd.read_excel(file_path, sheet_name='Car_Cost', index_col=0, header=0)

    df_stay_happy = pd.read_excel(file_path, sheet_name='Stay_Happy', index_col=0, header=0)
    

    # BUDGET
    BUDGET = int(df_basic.iloc[0, 0])
    # M = len(Set of hotels and airpots)
    M = int(df_basic.iloc[1, 0])
    I = int(df_basic.iloc[2, 0])
    P = int(df_basic.iloc[3, 0])
    D = int(df_basic.iloc[4, 0])
    K = int(df_basic.iloc[5, 0])

    # 第一天抵達的時間
    # 在這個 instance0 中值是 540 = 540 / 60 = 早上 9:00
    Day1Arrival = df_basic.iloc[6, 0]
    print(Day1Arrival)

    LH = df_hotel_time.iloc[0:df_hotel_time.shape[0], 0]
    RH = df_hotel_time.iloc[0:df_hotel_time.shape[0], 1]
    

    STAY = df_stay_happy.iloc[0:df_stay_happy.shape[0], 0]  # stay time
    HAPPINESS = df_stay_happy.iloc[0:df_stay_happy.shape[0], 1]  # happiness

    ### 接下來會把不同交通方式所需的時間矩陣存到一個字典 DURATION 中 ###
    # 設一個變數存取不同地點到不同地點走路所需的時間矩陣
    walk_time = np.zeros((df_walk_time.shape[0], df_walk_time.shape[1]))
    for i in range(df_walk_time.shape[0]):
        for j in range(df_walk_time.shape[1]):
            walk_time[i][j] = df_walk_time.iloc[i, j]
    
    # 設一個變數存取不同地點到不同地點搭火車所需的時間矩陣
    train_time = np.zeros((df_train_time.shape[0], df_train_time.shape[1]))
    for i in range(df_train_time.shape[0]):
        for j in range(df_train_time.shape[1]):
            train_time[i][j] = df_train_time.iloc[i, j]
    
    # 設一個變數存取不同地點到不同地點搭計程車所需的時間矩陣
    car_time = np.zeros((df_car_time.shape[0], df_car_time.shape[1]))
    for i in range(df_car_time.shape[0]):
        for j in range(df_car_time.shape[1]):
            car_time[i][j] = df_car_time.iloc[i, j]

    DURATION = {
        'Walk': walk_time,
        'Train': train_time,
        'Car': car_time
    }

    ### 接下來會把不同交通方式所需的費用矩陣存到一個字典 C_TRAVEL 中 ###
    # 設一個變數存取不同地點到不同地點搭火車所需的花費矩陣
    train_cost = np.zeros((df_train_cost.shape[0], df_train_cost.shape[1]))
    for i in range(df_train_cost.shape[0]):
        for j in range(df_train_cost.shape[1]):
            train_cost[i][j] = df_train_cost.iloc[i, j]

    # 設一個變數存取不同地點到不同地點搭計程車所需的花費矩陣
    car_cost = np.zeros((df_car_cost.shape[0], df_car_cost.shape[1]))
    for i in range(df_car_cost.shape[0]):
        for j in range(df_car_cost.shape[1]):
            car_cost[i][j] = df_car_cost.iloc[i, j]

    # Walk cost
    walk_cost = np.zeros((df_train_cost.shape[0], df_train_cost.shape[1]))


    # 把兩種交通方式的花費矩陣包裝到一個字典中
    C_TRAVEL = {
        'Walk' : walk_cost,
        'Train': train_cost,
        'Car': car_cost
    }

    C_HOTEL = np.zeros((df_hotel_cost.shape[0], df_hotel_cost.shape[1]))
    for i in range(df_hotel_cost.shape[0]):
        for j in range(df_hotel_cost.shape[1]):
            C_HOTEL[i][j] = df_hotel_cost.iloc[i, j]

    C_ATTRACTION = np.zeros(df_attraction_cost.shape[0])
    for i in range(df_attraction_cost.shape[0]):
            C_ATTRACTION[i] = df_attraction_cost.iloc[i]

    ATTRACTION_OPEN = np.zeros((df_attrcation_close.shape[0], df_attrcation_close.shape[1]))
    for i in range(df_attrcation_open.shape[0]):
        for j in range(df_attrcation_open.shape[1]):
            ATTRACTION_OPEN[i][j] = df_attrcation_open.iloc[i, j]

    ATTRACTION_CLOSE = np.zeros((df_attrcation_close.shape[0], df_attrcation_close.shape[1]))
    for i in range(df_attrcation_close.shape[0]):
        for j in range(df_attrcation_close.shape[1]):
            ATTRACTION_CLOSE[i][j] = df_attrcation_close.iloc[i, j]

    # 把參數包裝到一個字典中傳回
    results = {
        'BUDGET': BUDGET,
        'M': M,
        'I': I,
        'P': P,
        'D': D,
        'K': K,
        'LH': LH,
        'RH': RH,
        'Day1Arrival': Day1Arrival,
        'STAY': STAY,
        'HAPPINESS': HAPPINESS,
        'DURATION': DURATION,
        'C_TRAVEL': C_TRAVEL,
        'C_HOTEL': C_HOTEL,
        'C_ATTRACTION': C_ATTRACTION,
        'ATTRACTION_OPEN': ATTRACTION_OPEN,
        'ATTRACTION_CLOSE': ATTRACTION_CLOSE
    }
    
    return results

In [2]:
import pandas as pd
import numpy as np  
# Read Excel file and load data
file_path = "Instance1_0_real.xlsx"

data = load_file(file_path)

budget = data['BUDGET']
num_days = data['D']
num_hotels = data['M']  
num_attractions = data['I']
num_places = data['P']
num_transport_modes = data['K']

# S_M = [m for m in range(1, data['M'] + 1)]  #  the first hotel is the starting airport and the last hotel is the leaving airport
# S_I = [i for i in range(1, data['I'] + 1)]
# S_P = [p for p in range(1, data['I'] + data['M'] + 1)]
# S_D = [d for d in range(1, data['D'] + 1)]
# S_K = [k for k in range(1, data['K'] + 1)]

S_M = [m for m in range(0, data['M'])]  #  the first hotel is the starting airport and the last hotel is the leaving airport
S_I = [i for i in range(0, data['I'])]
S_P = [p for p in range(0, data['I'] + data['M'])]
S_D = [d for d in range(0, data['D'])]
S_K = [k for k in range(0, data['K'])]


# 第一天抵達機場時間
arrival_time_day1 = data['Day1Arrival'] # 需要從 Excel 讀取

# 每天離開旅館的時間 (不包含第一天和最後一天)
departure_time_hotel = data['LH'] # 需要從 Excel 讀取
departure_time_hotel = departure_time_hotel.reset_index(drop=True)

# 每天返回旅館的最晚時間
return_time_hotel = data['RH']    # 需要從 Excel 讀取
return_time_hotel = return_time_hotel.reset_index(drop=True)

# 每個景點的停留時間 (表格，索引為景點 i)
stay_duration = data['STAY']      # 需要從 Excel 讀取 (DataFrame 或 dict)
stay_duration = stay_duration.reset_index(drop=True)

# 每個景點的成本 (表格，索引為景點 i)
spot_costs = data['C_ATTRACTION']         # 需要從 Excel 讀取 (DataFrame 或 dict)

# 每個景點的幸福值 (表格，索引為景點 i)
happiness_values = data['HAPPINESS']    # 需要從 Excel 讀取 (DataFrame 或 dict)
happiness_values = happiness_values.reset_index(drop=True)

# 每個景點每天的開放時間 (表格，索引為景點 i 和天 d)
open_times = data['ATTRACTION_OPEN']          # 需要從 Excel 讀取 (DataFrame 或 dict)

# 每個景點每天的關閉時間 (表格，索引為景點 i 和天 d)
close_times = data['ATTRACTION_CLOSE']         # 需要從 Excel 讀取 (DataFrame 或 dict)

# 旅館每天的住宿成本 (表格，索引為旅館 m 和天 d，不包含起始和結束機場)
hotel_costs = data['C_HOTEL']        # 需要從 Excel 讀取 (DataFrame 或 dict)

# 地點 p 到地點 q 使用交通方式 k 的交通時間 (表格，索引為 p, q, k)
transport_times = data['DURATION']      # 需要從 Excel 讀取 (DataFrame 或 MultiIndex DataFrame 或 dict)
transport_times = np.stack(list(transport_times.values()))
# 地點 p 到地點 q 使用交通方式 k 的交通成本 (表格，索引為 p, q, k)
transport_costs = data['C_TRAVEL']     # 需要從 Excel 讀取 (DataFrame 或 MultiIndex DataFrame 或 dict)
transport_costs = np.stack(list(transport_costs.values()))

df_car_time = pd.read_excel(file_path, sheet_name='Car_Time', index_col=0, header=0)
place_names = df_car_time.index.tolist()

# 建立從 1 開始的對應 dictionary
place_names_dict = {i: name for i, name in enumerate(place_names)}

print(f"Budget: {budget}")
print(f"Number of days: {num_days}")
print(f"Number of hotels: {num_hotels}")
print(f"Number of attractions: {num_attractions}")
print(f"Number of places: {num_places}")
print(f"Number of transport modes: {num_transport_modes}")

print("Sets:")
print(f"S_M: {S_M}")
print(f"S_I: {S_I}")
print(f"S_P: {S_P}")
print(f"S_D: {S_D}")
print(f"S_K: {S_K}")

M = S_M
I = S_I
P = S_P
D = S_D
K = S_K

#重要!補0
stay_duration = pd.concat([stay_duration, pd.Series(0 for _ in range(num_hotels))], ignore_index=True)
stay_duration

BigM = 0
for d in S_D:
    hotel_candidates = list(S_M)[1:-1]  # 去掉機場（第0和最後一個）
    for h in hotel_candidates:
        cost = hotel_costs[d,h]  # 飯店索引偏移處理  
        BigM = max(BigM, cost)

print(f"Day 1 Arrival Time: {arrival_time_day1}")
print(f"Departure Time from Hotel: {departure_time_hotel}")
print(f"Return Time to Hotel: {return_time_hotel}")
print(f"Stay Duration: {stay_duration}")
print(f"Spot Costs: {spot_costs}")
print(f"Happiness Values: {happiness_values}")
print(f"Open Times: {open_times}")
print(f"Close Times: {close_times}")
print(f"Hotel Costs: {hotel_costs}")
print(f"Transport Times: {transport_times}", transport_times.shape)
print(f"Transport Costs: {transport_costs}", transport_costs.shape)

540
Budget: 100000
Number of days: 5
Number of hotels: 3
Number of attractions: 7
Number of places: 10
Number of transport modes: 3
Sets:
S_M: [0, 1, 2]
S_I: [0, 1, 2, 3, 4, 5, 6]
S_P: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
S_D: [0, 1, 2, 3, 4]
S_K: [0, 1, 2]
Day 1 Arrival Time: 540
Departure Time from Hotel: 0    540
1    600
2    540
3    540
4    660
Name: LH, dtype: int64
Return Time to Hotel: 0    1380
1    1380
2    1380
3    1380
4    1380
Name: RH, dtype: int64
Stay Duration: 0    120
1     60
2     90
3     80
4     60
5    180
6    240
7      0
8      0
9      0
dtype: int64
Spot Costs: [717.   0.   0. 696.   0.   0.   0.]
Happiness Values: 0    4.5
1    4.7
2    4.6
3    4.4
4    4.2
5    4.6
6    4.3
Name: Happiness, dtype: float64
Open Times: [[600. 600. 600. 600. 600.]
 [360. 360. 360. 360. 360.]
 [400. 400. 400. 400. 400.]
 [540. 540. 540. 540. 540.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]]
Close Times: [[1260. 1260. 1260. 1260. 1260.]

In [3]:
#在玩完一個景點後決定要不要換cluster 
def cluster_switching_decision(
    current_cluster,
    visited,
    get_cluster_score,
    get_nearest_high_score_cluster,
    d
):
    """
    Decide the next cluster to use based on remaining scores and hotel cluster.
    Returns the new current_cluster to use (may be the same as before).
    """
    remaining_score_in_current = get_cluster_score(current_cluster, visited)
    next_best_cluster, next_best_score = get_nearest_high_score_cluster(current_cluster, current_cluster, d)

    print(f"  Remaining score in current cluster: {remaining_score_in_current:.1f}, next best cluster: {next_best_cluster} score {next_best_score:.1f}")

    if next_best_score > 0 and remaining_score_in_current < next_best_score / 4:
        print(f"  !! Switching cluster: current {current_cluster} remaining score {remaining_score_in_current:.1f} < 1/4 of cluster {next_best_cluster} score {next_best_score:.1f}")
        return next_best_cluster
    else:
        print(f"  >> Stay in cluster {current_cluster} for next day")
        return current_cluster

In [4]:
#一天玩完了如果該cluster沒有旅館怎麼辦？
def hotel_cluster_decision(
    current_cluster,
    day_hotel_id,
    visited,
    id_to_cluster,
    get_cluster_score,
):
    remaining_score_in_current = get_cluster_score(current_cluster, visited)

    cluster_of_hotel = id_to_cluster.get(day_hotel_id, current_cluster)
    hotel_cluster_score = get_cluster_score(cluster_of_hotel, visited)

    if current_cluster != cluster_of_hotel:
        if remaining_score_in_current > hotel_cluster_score * 0.4:
            print(f"  >> Will return to current cluster {current_cluster} tomorrow")
            return current_cluster
        else:
            print(f"  !! Stay in hotel cluster {cluster_of_hotel} tomorrow due to better score")
            return cluster_of_hotel
    else:
        return current_cluster     


In [5]:
#修改的

import numpy as np
from sklearn.cluster import DBSCAN

# ==== 使用 P 代替 all_ids ====
id_to_index = {pid: idx for idx, pid in enumerate(S_P)}
index_to_id = {idx: pid for pid, idx in id_to_index.items()}

# ==== 執行 DBSCAN ====
db = DBSCAN(eps=20, min_samples=1, metric='precomputed')
labels = db.fit_predict(transport_times[2])  # Use Car as index 2 for numpy array

# ==== 建立 cluster_map 和 id_to_cluster ====
cluster_map = {}
id_to_cluster = {}
for idx, label in enumerate(labels):
    pid = S_P[idx]
    cluster_map.setdefault(label, []).append(pid)
    id_to_cluster[pid] = label
print(cluster_map)

# ==== 建立 place_score 和 place_score_dict ====
place_score = []
for i in S_I:
    name = place_names_dict[i]  # ID 轉成名稱
    h = happiness_values[i] if hasattr(happiness_values, '__getitem__') else happiness_values.get(name, 0)
    t = stay_duration[i] if hasattr(stay_duration, '__getitem__') else stay_duration.get(name, 0)
    score = h / (t + 1e-6)  # 避免除以零
    place_score.append((i, score))  # 保留 ID 當 key，後面好查
place_score.sort(key=lambda x: x[1], reverse=True)
place_score_dict = dict(place_score)

# ==== 計算 cluster 幸福分數總和 ====
cluster_scores = {}
for label, members in cluster_map.items():
    total_score = sum(place_score_dict.get(pid, 0) for pid in members if pid in S_I)
    cluster_scores[label] = total_score

# 數字對交通方式
transport_means_dict = {
    0: "Walk",
    1: "Train",
    2: "Car"
}
transport_means_to_id = {v: k for k, v in transport_means_dict.items()}
alpha = 1e-6
total_cost = 0
cost_in_day = np.zeros(len(S_D))
daily_budget = budget / len(S_D)

# ===== 選擇交通方式函數 =====
def get_best_travel_by_ratio(p1, p2, d, alpha=1e-6):
    best_score = -float('inf')
    best_time = BigM
    best_cost = BigM
    best_mode = None

    # 計算 walk 的 travel time，作為比較基準
    try:
        t_walk = transport_times[0, p1, p2]  # 0: Walk
    except Exception:
        t_walk = BigM

    if t_walk >= BigM:
        return best_time, best_cost, best_mode  # 若走路無法到，則整組無效

    for k in S_K:
        t = transport_times[k, p1, p2]
        c = transport_costs[k, p1, p2]
        if t >= BigM or c >= BigM:
            continue
        cost_in_day_after_mode = cost_in_day[d] + c
        time_saving_ratio = (t_walk - t) / (t_walk + alpha)
        cost_ratio = cost_in_day_after_mode / daily_budget
        score = time_saving_ratio / (cost_ratio + alpha)
        if score > best_score:
            best_score = score
            best_time = t
            best_cost = c
            best_mode = k
    return best_time, best_cost, best_mode

# ===== 幫助函數：取得某 cluster 尚未拜訪景點的總分 =====
def get_cluster_score(cluster_id, visited_set):
    return sum(place_score_dict.get(pid, 0) for pid in cluster_map[cluster_id] if pid in S_I and pid not in visited_set)

# ===== 幫助函數：從其他 cluster 中找到最近且幸福值最高的 cluster =====
def get_nearest_high_score_cluster(current_cl, excluded, d):
    candidates = [cl for cl in cluster_map if cl != excluded and cl != current_cl]
    best_score, best_cl = -1, None
    for cl in candidates:
        min_dist = float('inf')
        for p1 in cluster_map[current_cl]:
            if p1 in visited:
                continue
            for p2 in cluster_map[cl]:
                if p2 in visited:
                    continue
                t, _, _ = get_best_travel_by_ratio(p1, p2, d)
                if t < min_dist:
                    min_dist = t
        score = get_cluster_score(cl,visited) / (min_dist + 1e-6)
        if score > best_score:
            best_score, best_cl = score, cl
    return best_cl, get_cluster_score(best_cl,visited)

# ==== 計算 cluster 到來機場距離 ====
airport_start = S_M[0]
airport_end = S_M[-1]
cluster_to_airport_distance = {}
for label, members in cluster_map.items():
    min_dist = float('inf')
    for pid in members:
        t, c, mode = get_best_travel_by_ratio(airport_start, pid, 0)
        if t < min_dist:
            min_dist = t
    cluster_to_airport_distance[label] = min_dist

# ==== 綜合起點分數並選起始 cluster ====
cluster_start_scores = {}
for label in cluster_map.keys():
    happiness = cluster_scores.get(label, 0)
    distance = cluster_to_airport_distance.get(label, float('inf'))
    cluster_start_scores[label] = happiness / (distance + 1e-6)
start_cluster = max(cluster_start_scores.items(), key=lambda x: x[1])[0]

##繼續處理下面的：

# ===== 行程規劃主流程 =====
itinerary = []
visited = set()
total_happiness = 0
current_cluster = start_cluster

for d in S_D:
    current_time = arrival_time_day1 if d == 0 else departure_time_hotel[d]
    current_location = airport_start if d == 0 else itinerary[-1]['hotel']
    day_plan = []
    day_hotel_id = None

    print(f"\nDay {d} planning...")
    print(f"\n==== Day {d} Start ====")
    print(f"  Start location: {current_location} (可能是機場或前一晚飯店)")
    print(f"  Start time: {current_time:.2f} min, Budget left: {budget - total_cost:.2f}")
    print(f"  Visited so far: {visited}")

    # --- Dynamic cluster switching loop ---
    # Use a while loop to allow restarting when cluster switches
    while True:
        cluster_place_list = sorted(
            cluster_map[current_cluster],
            key=lambda x: place_score_dict.get(x, 0),
            reverse=True
        )
        switched = False
        for pid in cluster_place_list:
            if pid in visited or pid not in S_I:
                continue
            open_t = open_times[pid, d]
            close_t = close_times[pid, d]

            travel_t, travel_c, best_k = get_best_travel_by_ratio(current_location, pid, d)
            name = place_names_dict[pid]
            visit_t = stay_duration[pid]
            arrival_time = current_time + travel_t

            # ===== 新增：如果太早到，可以選擇等待 =====
            wait_time = 0
            if arrival_time < open_t:
                # Try waiting until open
                wait_time = open_t - arrival_time
                new_arrival_time = arrival_time + wait_time
                new_leave_time = new_arrival_time + visit_t
                
                print(f"      Arrive early ({arrival_time:.2f}), will wait {wait_time:.2f} min until open at {open_t}.")
                arrival_time = new_arrival_time
                leave_time = new_leave_time
                current_time += wait_time  # Add wait time to current time
            else:
                leave_time = arrival_time + visit_t

            # !!! Don't need to openning hours because we will wait
            # # Check if visit is possible (still within opening hours and budget)
            if leave_time > close_t: # arrival_time < open_t
                print(f"      SKIP: Out of opening hours (arrive {arrival_time:.2f}, leave {leave_time:.2f})")
                continue
            
            # leave_time = arrival_time + visit_t

            print(f"    Try place {pid}: open {open_t}, close {close_t}, stay {visit_t} min")
            print(f"      Travel from {current_location} by {best_k}: time {travel_t:.2f}, cost {travel_c:.2f}, arrival {arrival_time:.2f}, leave {leave_time:.2f}")

            # if arrival_time < open_t or leave_time > close_t:
            #     print(f"      SKIP: Out of opening hours (arrive {arrival_time:.2f}, leave {leave_time:.2f})")
            #     continue
            
            cost_at_spot = spot_costs[pid]

            if d == num_days:
                return_t, _, _ = get_best_travel_by_ratio(pid, airport_end, d)
            else:
                hotel_candidates = list(S_M)[1:-1]
                cluster_hotels = [h for h in cluster_map.get(current_cluster, []) if h in hotel_candidates]
                hotel_scores = []

                valid_hotels = cluster_hotels if cluster_hotels else [
                    h for cl, members in cluster_map.items() if cl != current_cluster
                    for h in members if h in hotel_candidates
                ]

                hotel_travel_times = []
                for h in valid_hotels:
                    t, _, _ = get_best_travel_by_ratio(pid, h, d)
                    hotel_cost = hotel_costs[d, h - S_M[0]]  # corrected index for hotel
                    if hotel_cost > 0 and t < BigM:
                        hotel_travel_times.append((h, t, hotel_cost))

                if hotel_travel_times:
                    t_max = max(t for _, t, _ in hotel_travel_times)
                    for h, t, hotel_cost in hotel_travel_times:
                        cost_in_day_after_mode = cost_in_day[d] + hotel_cost
                        time_saving_ratio = (t_max - t) / (t_max + alpha)
                        cost_ratio = cost_in_day_after_mode / budget
                        score = time_saving_ratio / (cost_ratio + alpha)
                        hotel_scores.append((h, t, score))

                if hotel_scores:
                    best_hotel = min(hotel_scores, key=lambda x: x[2])
                    day_hotel_id, return_t, _ = best_hotel
                else:
                    day_hotel_id = list(S_M)[1]
                    return_t, _, _ = get_best_travel_by_ratio(pid, day_hotel_id, d)

            if current_time + travel_t + visit_t + return_t > return_time_hotel[d]:
                print(f"      SKIP: Exceeds allowed return time ({current_time + travel_t + visit_t + return_t:.2f} > {return_time_hotel[d]})")
                continue
            if total_cost + travel_c + cost_at_spot > budget:
                print(f"      SKIP: Will exceed total budget ({total_cost + travel_c + cost_at_spot:.2f} > {budget})")
                continue

            # Visit the spot
            visited.add(pid)
            day_plan.append({
                'place': pid,
                'arrive': current_time + travel_t,
                'depart': current_time + travel_t + visit_t,
                'mode': best_k
            })
            total_cost += travel_c + cost_at_spot
            cost_in_day[d] += travel_c + cost_at_spot
            total_happiness += happiness_values[pid] if hasattr(happiness_values, '__getitem__') else happiness_values.get(name, 0)
            current_time += travel_t + visit_t
            current_location = pid

            # --- Dynamic cluster switching decision ---
            new_cluster = cluster_switching_decision(
                current_cluster,
                visited,
                get_cluster_score,
                get_nearest_high_score_cluster,
                d
            )
            if new_cluster != current_cluster:
                print(f"*** Switching to cluster {new_cluster} after visiting {pid}. Restarting spot selection. ***")
                current_cluster = new_cluster
                switched = True
                break  # Restart the while True loop with new cluster

        if not switched:
            break  # Done with the day's cluster, exit while loop

    if day_hotel_id is None:
        print(f"No valid hotel was selected for day {d}. Using previous hotel.")
        day_hotel_id = itinerary[-1]["hotel"] if itinerary else S_M[1]

    print(f"==== Day {d} End ====")
    print(f"  Visited today: {[p['place'] for p in day_plan]}")
    print(f"  End at hotel: {day_hotel_id}, Total cost so far: {total_cost:.2f}, Total happiness: {total_happiness}")
    print("-" * 40)

    new_cluster = hotel_cluster_decision(
        current_cluster,
        day_hotel_id,
        visited,
        id_to_cluster,
        get_cluster_score,
        )

    if new_cluster != current_cluster:
        print(f"** Switching to cluster {new_cluster} tomorrow, after visiting {pid} today. **")
        current_cluster = new_cluster

    if d != num_days-1:
        hotel_cost = hotel_costs[d, day_hotel_id - S_M[0]]  # corrected index for hotel
        total_cost += hotel_cost
        itinerary.append({'day': d, 'plan': day_plan, 'hotel': day_hotel_id})
    else:
        return_travel_time, _, _ = get_best_travel_by_ratio(current_location, airport_end, d)
        current_time += return_travel_time
        itinerary.append({'day': d, 'plan': day_plan, 'hotel': 'airport'})

# ===== 輸出總結 =====
print("\n=== 最終行程 ===")
for day_info in itinerary:
    print(f"Day {day_info['day']}:")
    for p in day_info['plan']:
        print(f"  Visit {p['place']} from {p['arrive']/60:.2f} to {p['depart']/60:.2f} by mode {p['mode']}")
    print(f"  Hotel: {day_info['hotel']}")
print(f"\nTotal cost: {total_cost}")
print(f"Total happiness: {total_happiness}")

{0: [0, 1, 4], 1: [2, 3, 5, 6, 8], 2: [7], 3: [9]}

Day 0 planning...

==== Day 0 Start ====
  Start location: 0 (可能是機場或前一晚飯店)
  Start time: 540.00 min, Budget left: 100000.00
  Visited so far: set()
    Try place 1: open 360.0, close 1020.0, stay 60 min
      Travel from 0 by 1: time 10.00, cost 38.00, arrival 550.00, leave 610.00
  Remaining score in current cluster: 0.1, next best cluster: 1 score 0.1
  >> Stay in cluster 0 for next day
    Try place 4: open 0.0, close 1440.0, stay 60 min
      Travel from 1 by 2: time 5.00, cost 330.00, arrival 615.00, leave 675.00
  Remaining score in current cluster: 0.0, next best cluster: 1 score 0.1
  >> Stay in cluster 0 for next day
    Try place 0: open 600.0, close 1260.0, stay 120 min
      Travel from 4 by 2: time 10.00, cost 330.00, arrival 685.00, leave 805.00
  Remaining score in current cluster: 0.0, next best cluster: 1 score 0.1
  !! Switching cluster: current 0 remaining score 0.0 < 1/4 of cluster 1 score 0.1
*** Switching to clus